logging:
  level:
    guru.springframework: debug
#spring:
#  jpa:
#    properties:
#      jakarta:
#        persistence:
#          schema-generation:
#            scripts:
#              action: drop-and-create
#              create-sources: metadata
#              drop-target: drop-and-create.sql
#              create-target: drop-and-create.sql
spring:
  flyway:
    enabled: false
