spring:
  datasource:
    username: restadmin
    password: password
    url: jdbc:mysql://localhost:3306/restdb?useUnicode=true&characterEncoding=UTF-8&serverTimezone=UTC
    driver-class-name: com.mysql.cj.jdbc.Driver
    hikari:
      pool-name: RestDB-Pool
      maximum-pool-size: 5

  jpa:
    database: mysql
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQLDialect
#        show_sql: true
#        format_sql: true
    hibernate:
      ddl-auto: update
    defer-datasource-initialization: true
#logging:
#  level:
#    org.hibernate.orm.jdbc.bind: trace